#!/bin/bash
# scribe self-extracting installer.
# Generated by build.sh from src/. Do not edit by hand.

set -u

SCRIBE_VERSION="__VERSION__"
SCRIBE_HOME="$HOME/.scribe"
CLAUDE_DIR="$HOME/.claude"
SETTINGS="$CLAUDE_DIR/settings.json"
COMMANDS_DIR="$CLAUDE_DIR/commands"

red()    { printf '\033[0;31m%s\033[0m\n' "$*"; }
green()  { printf '\033[0;32m%s\033[0m\n' "$*"; }
bold()   { printf '\033[1m%s\033[0m\n' "$*"; }

err() { red "scribe: $*" >&2; exit 1; }

bold "Welcome to scribe."
echo

# 1. Pre-flight checks.
case "$(uname -s)" in
  Darwin) PLATFORM="macos" ;;
  Linux)
    if [ -f /proc/version ] && grep -qi microsoft /proc/version; then
      PLATFORM="wsl"
    else
      PLATFORM="linux"
    fi
    ;;
  *) err "Unsupported OS: $(uname -s). scribe supports macOS and Linux." ;;
esac

case "$(uname -m)" in
  arm64|aarch64) ARCH="arm64" ;;
  x86_64|amd64)  ARCH="x86_64" ;;
  *) err "Unsupported architecture: $(uname -m)." ;;
esac

if [ "$PLATFORM" = "wsl" ]; then PLATFORM="linux"; fi
echo "  ✓ Detected $PLATFORM ($ARCH)"

if ! command -v claude >/dev/null 2>&1; then
  red "  ✗ Claude Code is not installed."
  echo
  echo "Install it from https://claude.com/claude-code, then re-run this script."
  exit 1
fi
echo "  ✓ Found Claude Code"

if [ ! -d "$HOME" ] || [ ! -w "$HOME" ]; then
  err "Cannot write to home directory $HOME."
fi

# 2. Extract files.
TMP=$(mktemp -d "${TMPDIR:-/tmp}/scribe-install.XXXXXX")
trap 'rm -rf "$TMP"' EXIT

# Decode the source payload.
PAYLOAD_B64=$(awk '/^__PAYLOAD_BEGIN__$/{flag=1; next} /^__PAYLOAD_END__$/{flag=0} flag' "$0")
echo "$PAYLOAD_B64" | base64 -d | tar xzf - -C "$TMP"

# Decode the right jq binary.
case "$PLATFORM-$ARCH" in
  macos-arm64)  JQ_KEY="JQ_MACOS_ARM64" ;;
  macos-x86_64) JQ_KEY="JQ_MACOS_X86_64" ;;
  linux-x86_64) JQ_KEY="JQ_LINUX_X86_64" ;;
  linux-arm64)  JQ_KEY="JQ_LINUX_ARM64" ;;
esac

JQ_B64=$(awk -v k="__${JQ_KEY}_BEGIN__" -v k2="__${JQ_KEY}_END__" '
  $0==k {flag=1; next} $0==k2 {flag=0} flag' "$0")
mkdir -p "$SCRIBE_HOME/bin"
echo "$JQ_B64" | base64 -d > "$SCRIBE_HOME/bin/jq"
chmod +x "$SCRIBE_HOME/bin/jq"
xattr -d com.apple.quarantine "$SCRIBE_HOME/bin/jq" 2>/dev/null || true

# 3. Move source files into place.
mkdir -p "$SCRIBE_HOME/hooks" "$SCRIBE_HOME/templates" "$SCRIBE_HOME/library"
cp "$TMP/src/bin/scribe" "$SCRIBE_HOME/bin/scribe"
chmod +x "$SCRIBE_HOME/bin/scribe"
cp "$TMP/src/hooks/"*.sh "$SCRIBE_HOME/hooks/"
chmod +x "$SCRIBE_HOME/hooks/"*.sh
cp -R "$TMP/src/templates/." "$SCRIBE_HOME/templates/"
cp "$TMP/src/installer/uninstall.sh" "$SCRIBE_HOME/uninstall.sh"
chmod +x "$SCRIBE_HOME/uninstall.sh"
echo "$SCRIBE_VERSION" > "$SCRIBE_HOME/VERSION"
echo "  ✓ Installed scribe to $SCRIBE_HOME"

# 4. Wire hooks into Claude Code via jq merge.
mkdir -p "$CLAUDE_DIR" "$COMMANDS_DIR"
JQ="$SCRIBE_HOME/bin/jq"

if [ ! -f "$SETTINGS" ]; then
  echo '{}' > "$SETTINGS"
fi

# Build the hooks blob.
SS_HOOK="$SCRIBE_HOME/hooks/session-start.sh"
ST_HOOK="$SCRIBE_HOME/hooks/stop.sh"

UPDATED=$("$JQ" \
  --arg ss "$SS_HOOK" \
  --arg st "$ST_HOOK" \
  '
  .hooks //= {}
  | .hooks.SessionStart //= []
  | .hooks.Stop //= []
  | .hooks.SessionStart |= map(select(.scribe != true))
  | .hooks.Stop |= map(select(.scribe != true))
  | .hooks.SessionStart += [{"scribe": true, "hooks": [{"type": "command", "command": $ss}]}]
  | .hooks.Stop += [{"scribe": true, "hooks": [{"type": "command", "command": $st}]}]
  ' "$SETTINGS")
echo "$UPDATED" > "$SETTINGS"
echo "  ✓ Wired hooks into $SETTINGS"

# 5. Install slash commands.
cp "$TMP/src/commands/"*.md "$COMMANDS_DIR/"
echo "  ✓ Installed slash commands to $COMMANDS_DIR"

# 6. Add to PATH.
RC=""
case "${SHELL:-}" in
  */zsh) RC="$HOME/.zshrc" ;;
  */bash) RC="$HOME/.bashrc" ;;
esac

if [ -n "$RC" ]; then
  PATH_LINE='export PATH="$HOME/.scribe/bin:$PATH"'
  if [ ! -f "$RC" ] || ! grep -qF "$PATH_LINE" "$RC"; then
    echo "" >> "$RC"
    echo "# scribe" >> "$RC"
    echo "$PATH_LINE" >> "$RC"
    echo "  ✓ Added scribe to your PATH ($RC)"
  else
    echo "  ✓ scribe already in PATH ($RC)"
  fi
fi

echo
green "Done."
echo
echo "What's next:"
echo "  1. Open Claude Code in any project (cd into your project, run \"claude\")."
echo "  2. Claude will ask once if you want to turn on auto-journaling there."
echo "  3. Say yes to enable, no to skip, \"not now\" to be asked again later."
echo
echo "To remove scribe later:"
echo "  bash ~/.scribe/uninstall.sh"
echo

exit 0

# Embedded payloads follow. Do not modify.
__PAYLOAD_BEGIN__
__PAYLOAD__
__PAYLOAD_END__
__JQ_MACOS_ARM64_BEGIN__
__JQ_MACOS_ARM64__
__JQ_MACOS_ARM64_END__
__JQ_MACOS_X86_64_BEGIN__
__JQ_MACOS_X86_64__
__JQ_MACOS_X86_64_END__
__JQ_LINUX_X86_64_BEGIN__
__JQ_LINUX_X86_64__
__JQ_LINUX_X86_64_END__
__JQ_LINUX_ARM64_BEGIN__
__JQ_LINUX_ARM64__
__JQ_LINUX_ARM64_END__
